name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JDK_VERSION: '17'
  JDK_DIST: 'temurin'
      
jobs:

  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK_DIST }} version ${{ env.JDK_VERSION }} and Maven cache
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: ${{ env.JDK_DIST }}
          cache: 'maven'
      - name: Execute Maven goal verify
        run: mvn --batch-mode --update-snapshots verify
