name: Java CI

on:
  pull_request:
    branches:
      - main

env:
  JDK_VERSION: '17'
  JDK_DIST: 'temurin'

jobs:

  build-site:
    name: Build Maven site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK_DIST }} version ${{ env.JDK_VERSION }} and Maven cache
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: ${{ env.JDK_DIST }}
          cache: 'maven'
      - name: Execute Maven goal site
        run: mvn --batch-mode --update-snapshots site
